module.exports = {
  apps: [
    {
      name: "crank-agent",
      cwd: "./agents/crank_agent",
      script: "npx",
      args: "ts-node src/index.ts",
      watch: false,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 10,
      env_file: ".env",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "../../.logs/crank-agent.log",
      error_file: "../../.logs/crank-agent.error.log",
    },
    {
      name: "oracle-agent",
      cwd: "./agents/oracle_agent",
      script: "npx",
      args: "ts-node src/index.ts",
      watch: false,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 10,
      env_file: ".env",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "../../.logs/oracle-agent.log",
      error_file: "../../.logs/oracle-agent.error.log",
    },
    {
      name: "lp-agent",
      cwd: "./agents/lp_agent",
      script: "npx",
      args: "ts-node src/index.ts",
      watch: false,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 10,
      env_file: ".env",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "../../.logs/lp-agent.log",
      error_file: "../../.logs/lp-agent.error.log",
    },
  ],
};
